apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - network-policy-rhpds.yaml
  - ui-oauth-resources.yaml
patches:
  - path: remove-lab-resources.yaml
  - path: praxis-rhpds-patch.yaml
  - path: ui-oauth-patch.yaml
